### ISSUE TITLE
Visuals Bookmark Favicon

### ISSUE THREAD

**Issue by bihe** [bihe/monorepo#166]
```css
.bookmark_favicon_select {
    /* width: 57px; */
    height: 57px;
    /* border: solid 1px; */
    display: block;
    background-color: #999;
    padding-left: 3px;
    padding-right: 3px;
}
```
